# Generated by Django 6.0.5 on 2026-05-26 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hours_spent',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
