# Generated by Django 6.0.5 on 2026-05-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogapp', '0002_remove_timesheet_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='task',
        ),
    ]
