# Generated by Django 6.0.5 on 2026-05-28 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogapp', '0004_timesheet_approved_at_timesheet_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='manager',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('PracticeHead', 'PracticeHead'), ('PrincipalSoftwareEngineer', 'PrincipalSoftwareEngineer'), ('HR', 'HR'), ('Sales', 'Sales'), ('CFO', 'CFO'), ('Employee', 'Employee')], default='Employee', max_length=100),
        ),
    ]
