# Generated by Django 6.0.5 on 2026-05-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_timesheet', '0002_timesheet_created_at_timesheet_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
