# Generated by Django 6.0.5 on 2026-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_timesheet', '0005_alter_timesheet_date_alter_timesheet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='team',
            field=models.CharField(choices=[('HR', 'HR'), ('SALES', 'Sales'), ('IT_ADMIN', 'IT Admin'), ('CFO', 'CFO'), ('PRACTICE_HEAD', 'Practice Head'), ('PRINCIPAL_ENGINEER', 'Principal Software Engineer')], default='HR', max_length=50),
        ),
    ]
